language: python
python:
  - "3.6"

install: 
  - pip install rx
  - python setup.py install
  - pip install coveralls
  - pip install coverage

script:  coverage run --source=reactive setup.py test
after_success:
  coveralls
